### ISSUE TITLE
Spin off kinect data into its own store to be fed by the input data, and contain other state data

### ISSUE THREAD

**Issue by timkettering** [SixSecondMonks/sos-display#48]
Right now seems that we have one store for everything, when we probably want to have the kinect data to be its own store, and it should also contain other state info (such as skeleton color, canvas coordinates, etc) so that other components of the app can inspect those vars without having to expose Overlay object.

**Comment by cantsin** [comment]
Related to #34

**Comment by cantsin** [comment]
Partially done. We still need to incorporate other kinect state info in the store.

**Comment by cantsin** [comment]
I think we have all of the kinect state data we can incorporate right now. Feel free to re-open if we find anything else.
